require_relative 'primative'
require_relative 'null'
# require_relative 'chain'
# require_relative 'construct'
# require_relative 'number'
# require_relative 'boolean'
# require_relative 'string'
# require_relative 'template'
# require_relative 'visor'
